using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Next_Future_ERP.Features.StoreIssues.Models;
using Next_Future_ERP.Features.StoreIssues.Services;
using Next_Future_ERP.Features.Warehouses.Models;
using Next_Future_ERP.Models;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Next_Future_ERP.Features.StoreIssues.ViewModels
{
    public partial class StoreIssueEditViewModel : ObservableObject
    {
        private readonly IStoreIssuesService _service;
        private readonly IIssueDestinationsService _destinationsService;

        [ObservableProperty] private StoreIssue model;
        [ObservableProperty] private bool isLoading;
        [ObservableProperty] private bool isEditMode;
        [ObservableProperty] private StoreIssueDetail? selectedDetail;

        public ObservableCollection<IssueDestination> Destinations { get; } = new();
        public ObservableCollection<Warehouse> Warehouses { get; } = new();
        public ObservableCollection<NextCurrency> Currencies { get; } = new();
        public ObservableCollection<StoreIssueDetail> Details { get; } = new();

        // Commands - all commands are auto-generated by [RelayCommand]
        public event EventHandler<bool>? CloseRequested;

        public StoreIssueEditViewModel(StoreIssue model, IStoreIssuesService service, IIssueDestinationsService destinationsService)
        {
            _service = service;
            _destinationsService = destinationsService;
            this.model = model;
            IsEditMode = model.IssueId > 0;

            // Subscribe to property changes to update button states
            PropertyChanged += (s, e) =>
            {
                if (e.PropertyName == nameof(Model) || e.PropertyName == nameof(SelectedDetail) || e.PropertyName == nameof(IsEditMode) || e.PropertyName == nameof(IsLoading))
                {
                    OnPropertyChanged(nameof(CanAddDetail));
                    OnPropertyChanged(nameof(CanDeleteDetail));
                    OnPropertyChanged(nameof(CanUpdateDetail));
                    OnPropertyChanged(nameof(CanPost));
                    OnPropertyChanged(nameof(CanSave));
                }
            };

            // Subscribe to Model property changes (if Model implements INotifyPropertyChanged)
            if (Model is INotifyPropertyChanged notifyModel)
            {
                notifyModel.PropertyChanged += (s, e) =>
                {
                    if (e.PropertyName == nameof(Model.IssueDestinationID) || 
                        e.PropertyName == nameof(Model.DefaultWarehouseId) || 
                        e.PropertyName == nameof(Model.Status) ||
                        e.PropertyName == nameof(Model.CurrencyId) ||
                        e.PropertyName == nameof(Model.ExchangeRate) ||
                        e.PropertyName == nameof(Model.IssueNumber) ||
                        e.PropertyName == nameof(Model.IssueDate))
                    {
                        OnPropertyChanged(nameof(CanAddDetail));
                        OnPropertyChanged(nameof(CanDeleteDetail));
                        OnPropertyChanged(nameof(CanUpdateDetail));
                        OnPropertyChanged(nameof(CanPost));
                        OnPropertyChanged(nameof(CanSave));
                    }
                };
            }
        }

        [RelayCommand]
        public async Task InitializeAsync()
        {
            try
            {
                IsLoading = true;
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.InitializeAsync: Starting initialization");

                // Clear collections first to prevent binding issues
                Destinations.Clear();
                Warehouses.Clear();
                Currencies.Clear();

                // Load destinations
                var destinations = await _destinationsService.GetAllAsync();
                // Add default empty item first
                Destinations.Add(new IssueDestination { DestinationID = 0, DestinationName = "اختر جهة صرف" });
                foreach (var dest in destinations.Where(d => d != null))
                {
                    Destinations.Add(dest);
                }

                // Load warehouses (TODO: Implement warehouse service)
                // Add default empty item first
                Warehouses.Add(new Warehouse { WarehouseID = 0, WarehouseName = "اختر مخزن" });
                // For now, add dummy data with null checks
                var warehouseData = new[]
                {
                    new Warehouse { WarehouseID = 1, WarehouseName = "مخزن رئيسي", IsActive = true },
                    new Warehouse { WarehouseID = 2, WarehouseName = "مخزن فرعي", IsActive = true }
                };
                foreach (var warehouse in warehouseData.Where(w => w != null))
                {
                    Warehouses.Add(warehouse);
                }

                // Load currencies (TODO: Implement currency service)
                // Add default empty item first
                Currencies.Add(new NextCurrency { CurrencyId = 0, CurrencyNameAr = "اختر عملة" });
                // For now, add dummy data with null checks
                var currencyData = new[]
                {
                    new NextCurrency { CurrencyId = 1, CurrencyNameAr = "ريال سعودي" },
                    new NextCurrency { CurrencyId = 2, CurrencyNameAr = "دولار أمريكي" }
                };
                foreach (var currency in currencyData.Where(c => c != null))
                {
                    Currencies.Add(currency);
                }

                // Load details if editing
                if (IsEditMode && Model.IssueId > 0)
                {
                    var details = await _service.GetDetailsAsync(Model.IssueId);
                    Details.Clear();
                    foreach (var detail in details)
                    {
                        Details.Add(detail);
                    }
                }

                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.InitializeAsync: Initialization completed");
                
                // Refresh button states after initialization
                RefreshButtonStates();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.InitializeAsync: Error: {ex.Message}");
                MessageBox.Show($"خطأ في تحميل البيانات: {ex.Message}", "خطأ", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                IsLoading = false;
            }
        }

        [RelayCommand]
        public async Task SaveAsync()
        {
            try
            {
                IsLoading = true;
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.SaveAsync: Starting save operation");

                // Validate required fields
                if (Model.IssueDestinationID <= 0)
                {
                    ShowMessageSync("يجب اختيار جهة الصرف", "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (Model.CurrencyId <= 0)
                {
                    ShowMessageSync("يجب اختيار العملة", "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (Model.ExchangeRate <= 0)
                {
                    ShowMessageSync("يجب إدخال سعر الصرف", "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (string.IsNullOrWhiteSpace(Model.IssueNumber))
                {
                    ShowMessageSync("يجب إدخال رقم المستند", "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (Model.IssueDate == default)
                {
                    ShowMessageSync("يجب اختيار تاريخ المستند", "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (IsEditMode)
                {
                    await _service.UpdateAsync(Model);
                    ShowMessageSync("تم تحديث المستند بنجاح", "نجح", MessageBoxImage.Information);
                }
                else
                {
                    // إضافة التفاصيل المحلية إلى المستند قبل الحفظ
                    if (Details.Any())
                    {
                        Model.Details = Details.ToList();
                        // تحديث IssueId للتفاصيل المحلية
                        foreach (var detail in Model.Details)
                        {
                            detail.IssueId = 0; // سيتم تحديثه تلقائياً عند الحفظ
                        }
                    }

                    var id = await _service.AddAsync(Model);
                    if (id > 0)
                    {
                        Model.IssueId = id;
                        IsEditMode = true;
                        
                        // تحديث IssueId للتفاصيل المحلية بعد الحفظ
                        foreach (var detail in Details)
                        {
                            detail.IssueId = id;
                        }
                        
                        ShowMessageSync("تم حفظ المستند بنجاح", "نجح", MessageBoxImage.Information);
                    }
                }

                CloseRequested?.Invoke(this, true);
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.SaveAsync: Save completed successfully");
                
                // Refresh button states after save
                RefreshButtonStates();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.SaveAsync: Error: {ex.Message}");
                ShowMessageSync($"خطأ في حفظ المستند: {ex.Message}", "خطأ", MessageBoxImage.Error);
            }
            finally
            {
                IsLoading = false;
            }
        }

        [RelayCommand]
        public async Task PostAsync()
        {
            try
            {
                IsLoading = true;
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.PostAsync: Starting post operation");

                if (Model.IssueId <= 0)
                {
                    // Save first if not saved
                    await SaveAsync();
                }

                if (Model.IssueId > 0)
                {
                    // Check if there are details
                    if (Details.Count == 0)
                    {
                        MessageBox.Show("يجب إضافة تفاصيل للمستند قبل الترحيل", "تنبيه", MessageBoxButton.OK, MessageBoxImage.Warning);
                        return;
                    }

                    var success = await _service.PostAsync(Model.IssueId);
                    if (success)
                    {
                        MessageBox.Show("تم ترحيل المستند بنجاح", "نجح", MessageBoxButton.OK, MessageBoxImage.Information);
                        CloseRequested?.Invoke(this, true);
                    }
                }

                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.PostAsync: Post completed");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.PostAsync: Error: {ex.Message}");
                MessageBox.Show($"خطأ في ترحيل المستند: {ex.Message}", "خطأ", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                IsLoading = false;
            }
        }

        [RelayCommand]
        public async Task CancelAsync()
        {
            try
            {
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.CancelAsync: Starting cancel operation");
                
                // Check if there are unsaved changes
                if (Model.IssueId <= 0 && Details.Any())
                {
                    var result = MessageBox.Show("يوجد تفاصيل غير محفوظة. هل تريد المتابعة؟", "تأكيد", 
                        MessageBoxButton.YesNo, MessageBoxImage.Question);
                    
                    if (result == MessageBoxResult.No)
                    {
                        return;
                    }
                }
                
                CloseRequested?.Invoke(this, false);
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.CancelAsync: Cancel completed");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.CancelAsync: Error: {ex.Message}");
                ShowMessageSync($"خطأ في إلغاء العملية: {ex.Message}", "خطأ", MessageBoxImage.Error);
            }
        }

        [RelayCommand]
        public async Task AddDetailAsync()
        {
            try
            {
                System.Diagnostics.Debug.WriteLine("=== AddDetailAsync START ===");
                System.Diagnostics.Debug.WriteLine($"Model.IssueDestinationID: {Model.IssueDestinationID}");
                System.Diagnostics.Debug.WriteLine($"Model.DefaultWarehouseId: {Model.DefaultWarehouseId}");
                System.Diagnostics.Debug.WriteLine($"Model.Status: {Model.Status}");
                System.Diagnostics.Debug.WriteLine($"CanAddDetail: {CanAddDetail}");

                // التحقق من البيانات المطلوبة مع رسائل واضحة
                if (Model.IssueDestinationID <= 0)
                {
                    var errorMsg = "يجب اختيار جهة الصرف أولاً من القائمة المنسدلة";
                    System.Diagnostics.Debug.WriteLine($"ERROR: {errorMsg}");
                    ShowMessageSync(errorMsg, "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (Model.DefaultWarehouseId == null || Model.DefaultWarehouseId <= 0)
                {
                    var errorMsg = "يجب اختيار المخزن الافتراضي أولاً من القائمة المنسدلة";
                    System.Diagnostics.Debug.WriteLine($"ERROR: {errorMsg}");
                    ShowMessageSync(errorMsg, "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                if (Model.Status != 0)
                {
                    var errorMsg = "لا يمكن إضافة تفاصيل للمستندات المرحلة أو الملغية";
                    System.Diagnostics.Debug.WriteLine($"ERROR: {errorMsg}");
                    ShowMessageSync(errorMsg, "تنبيه", MessageBoxImage.Warning);
                    return;
                }

                // إذا كان المستند جديد (IssueId = 0)، أضف التفصيل محلياً فقط
                if (Model.IssueId <= 0)
                {
                    var newDetail = new StoreIssueDetail
                    {
                        IssueId = 0, // سيتم تحديثه عند حفظ المستند
                        LineNo = Details.Count + 1,
                        Quantity = 1,
                        UnitCost = 0,
                        CurrencyId = Model.CurrencyId,
                        ExchangeRate = Model.ExchangeRate,
                        WarehouseId = Model.DefaultWarehouseId.Value,
                        ItemId = 0 // سيتم تحديثه لاحقاً
                    };

                    Details.Add(newDetail);
                    OnPropertyChanged(nameof(CanAddDetail)); // تحديث حالة الزر
                    System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.AddDetailAsync: Added detail locally for new document");
                    
                    var localSuccessMsg = "تم إضافة التفصيل محلياً. سيتم حفظه عند حفظ المستند";
                    System.Diagnostics.Debug.WriteLine($"SUCCESS: {localSuccessMsg}");
                    ShowMessageSync(localSuccessMsg, "معلومات", MessageBoxImage.Information);
                    System.Diagnostics.Debug.WriteLine("=== AddDetailAsync END (Local) ===");
                    return;
                }

                // للمستندات المحفوظة، أضف التفصيل في قاعدة البيانات
                var newDetailForDb = new StoreIssueDetail
                {
                    IssueId = Model.IssueId,
                    LineNo = Details.Count + 1,
                    Quantity = 1,
                    UnitCost = 0,
                    CurrencyId = Model.CurrencyId,
                    ExchangeRate = Model.ExchangeRate,
                    WarehouseId = Model.DefaultWarehouseId.Value
                };

                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.AddDetailAsync: Creating detail with IssueId: {newDetailForDb.IssueId}, WarehouseId: {newDetailForDb.WarehouseId}");

                await _service.AddDetailAsync(newDetailForDb);
                
                // Refresh details
                var details = await _service.GetDetailsAsync(Model.IssueId);
                Details.Clear();
                foreach (var detail in details)
                {
                    Details.Add(detail);
                }

                // Refresh model totals
                var updatedModel = await _service.GetByIdAsync(Model.IssueId);
                if (updatedModel != null)
                {
                    Model.TotalAmount = updatedModel.TotalAmount;
                }

                var dbSuccessMsg = "تم إضافة التفصيل بنجاح";
                System.Diagnostics.Debug.WriteLine($"SUCCESS: {dbSuccessMsg}");
                ShowMessageSync(dbSuccessMsg, "نجح", MessageBoxImage.Information);
                System.Diagnostics.Debug.WriteLine("=== AddDetailAsync END (Database) ===");
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.AddDetailAsync: Detail added successfully");
            }
            catch (Exception ex)
            {
                var errorMsg = $"خطأ في إضافة التفصيل: {ex.Message}";
                System.Diagnostics.Debug.WriteLine($"CRITICAL ERROR: {errorMsg}");
                System.Diagnostics.Debug.WriteLine($"Stack Trace: {ex.StackTrace}");
                ShowMessageSync(errorMsg, "خطأ", MessageBoxImage.Error);
                System.Diagnostics.Debug.WriteLine("=== AddDetailAsync END (Error) ===");
            }
        }

        [RelayCommand]
        public async Task DeleteDetailAsync()
        {
            try
            {
                if (SelectedDetail == null)
                {
                    MessageBox.Show("يرجى اختيار التفصيل المراد حذفه", "تنبيه", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                var result = MessageBox.Show("هل أنت متأكد من حذف هذا التفصيل؟", "تأكيد الحذف", MessageBoxButton.YesNo, MessageBoxImage.Question);
                if (result == MessageBoxResult.Yes)
                {
                    // إذا كان المستند جديد، احذف التفصيل محلياً فقط
                    if (Model.IssueId <= 0)
                    {
                        Details.Remove(SelectedDetail);
                        OnPropertyChanged(nameof(CanAddDetail)); // تحديث حالة الزر
                        MessageBox.Show("تم حذف التفصيل محلياً", "نجح", MessageBoxButton.OK, MessageBoxImage.Information);
                        System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.DeleteDetailAsync: Detail removed locally");
                        return;
                    }

                    // للمستندات المحفوظة، احذف من قاعدة البيانات
                    await _service.DeleteDetailAsync(SelectedDetail.DetailId);
                    
                    // Refresh details
                    var details = await _service.GetDetailsAsync(Model.IssueId);
                    Details.Clear();
                    foreach (var detail in details)
                    {
                        Details.Add(detail);
                    }

                    // Refresh model totals
                    var updatedModel = await _service.GetByIdAsync(Model.IssueId);
                    if (updatedModel != null)
                    {
                        Model.TotalAmount = updatedModel.TotalAmount;
                    }

                    MessageBox.Show("تم حذف التفصيل بنجاح", "نجح", MessageBoxButton.OK, MessageBoxImage.Information);
                    System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.DeleteDetailAsync: Detail deleted successfully");
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.DeleteDetailAsync: Error: {ex.Message}");
                MessageBox.Show($"خطأ في حذف التفصيل: {ex.Message}", "خطأ", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        [RelayCommand]
        public async Task UpdateDetailAsync()
        {
            try
            {
                if (SelectedDetail == null) 
                {
                    MessageBox.Show("يرجى اختيار التفصيل المراد تحديثه", "تنبيه", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                if (SelectedDetail.Quantity <= 0)
                {
                    MessageBox.Show("الكمية يجب أن تكون أكبر من صفر", "تنبيه", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                if (SelectedDetail.UnitCost < 0)
                {
                    MessageBox.Show("تكلفة الوحدة يجب أن تكون أكبر من أو تساوي صفر", "تنبيه", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                await _service.UpdateDetailAsync(SelectedDetail);
                
                // Refresh details
                var details = await _service.GetDetailsAsync(Model.IssueId);
                Details.Clear();
                foreach (var detail in details)
                {
                    Details.Add(detail);
                }

                // Refresh model totals
                var updatedModel = await _service.GetByIdAsync(Model.IssueId);
                if (updatedModel != null)
                {
                    Model.TotalAmount = updatedModel.TotalAmount;
                }

                MessageBox.Show("تم تحديث التفصيل بنجاح", "نجح", MessageBoxButton.OK, MessageBoxImage.Information);
                System.Diagnostics.Debug.WriteLine("StoreIssueEditViewModel.UpdateDetailAsync: Detail updated successfully");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"StoreIssueEditViewModel.UpdateDetailAsync: Error: {ex.Message}");
                MessageBox.Show($"خطأ في تحديث التفصيل: {ex.Message}", "خطأ", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        // Properties for UI binding
        public bool CanPost => Model.Status == 0; // Only Draft
        public bool CanSave => !IsLoading && Model.Status == 0 && 
                              Model.IssueDestinationID > 0 && 
                              Model.CurrencyId > 0 && 
                              Model.ExchangeRate > 0 && 
                              !string.IsNullOrWhiteSpace(Model.IssueNumber) && 
                              Model.IssueDate != default;
        public string WindowTitle => IsEditMode ? "تعديل مستند الصرف" : "إضافة مستند صرف جديد";
        
        public bool CanAddDetail => Model.Status == 0 && Model.IssueDestinationID > 0 && Model.DefaultWarehouseId.HasValue && Model.DefaultWarehouseId.Value > 0;
        public bool CanDeleteDetail => SelectedDetail != null && Model.Status == 0;
        public bool CanUpdateDetail => SelectedDetail != null && Model.Status == 0;

        // Method to manually refresh button states
        public void RefreshButtonStates()
        {
            OnPropertyChanged(nameof(CanAddDetail));
            OnPropertyChanged(nameof(CanDeleteDetail));
            OnPropertyChanged(nameof(CanUpdateDetail));
            OnPropertyChanged(nameof(CanPost));
            OnPropertyChanged(nameof(CanSave));
        }

        // Test method to verify command is working
        public void TestAddDetailCommand()
        {
            System.Diagnostics.Debug.WriteLine("TestAddDetailCommand: Command is accessible");
            
            // Test with simple message
            var testMsg = $"Test: IssueDestinationID={Model.IssueDestinationID}, DefaultWarehouseId={Model.DefaultWarehouseId}";
            System.Diagnostics.Debug.WriteLine(testMsg);
            
            // Test validation logic
            if (Model.IssueDestinationID <= 0)
            {
                ShowMessageSync("يجب اختيار جهة الصرف أولاً من القائمة المنسدلة", "تنبيه", MessageBoxImage.Warning);
                return;
            }

            if (Model.DefaultWarehouseId == null || Model.DefaultWarehouseId <= 0)
            {
                ShowMessageSync("يجب اختيار المخزن الافتراضي أولاً من القائمة المنسدلة", "تنبيه", MessageBoxImage.Warning);
                return;
            }

            // Test button states
            var buttonStates = $"CanAddDetail: {CanAddDetail}, CanSave: {CanSave}, CanDeleteDetail: {CanDeleteDetail}";
            System.Diagnostics.Debug.WriteLine($"Button States: {buttonStates}");

            // Test message display
            ShowMessageSync($"الأمر يعمل!\n{testMsg}\n\n{buttonStates}", "اختبار", MessageBoxImage.Information);
            
            // Additional test - try to show a simple message
            try
            {
                MessageBox.Show("رسالة اختبار بسيطة", "اختبار مباشر");
                System.Diagnostics.Debug.WriteLine("Direct MessageBox test successful");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Direct MessageBox test failed: {ex.Message}");
            }
        }

        // Helper method to show messages asynchronously
        private async Task ShowMessageAsync(string message, string title, MessageBoxImage icon)
        {
            try
            {
                await Task.Run(() =>
                {
                    System.Windows.Application.Current.Dispatcher.Invoke(() =>
                    {
                        try
                        {
                            MessageBox.Show(message, title, MessageBoxButton.OK, icon);
                            System.Diagnostics.Debug.WriteLine($"MessageBox shown: {title} - {message}");
                        }
                        catch (Exception ex)
                        {
                            System.Diagnostics.Debug.WriteLine($"MessageBox error: {ex.Message}");
                            // Fallback to console output
                            Console.WriteLine($"MESSAGE: {title} - {message}");
                        }
                    });
                });
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"ShowMessageAsync error: {ex.Message}");
                // Ultimate fallback
                Console.WriteLine($"FALLBACK MESSAGE: {title} - {message}");
            }
        }

        // Alternative synchronous method for testing
        private void ShowMessageSync(string message, string title, MessageBoxImage icon)
        {
            try
            {
                // Try direct MessageBox first
                MessageBox.Show(message, title, MessageBoxButton.OK, icon);
                System.Diagnostics.Debug.WriteLine($"MessageBox shown (sync): {title} - {message}");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"MessageBox sync error: {ex.Message}");
                try
                {
                    // Fallback to simple message
                    MessageBox.Show(message, title);
                    System.Diagnostics.Debug.WriteLine($"MessageBox fallback shown: {title} - {message}");
                }
                catch (Exception ex2)
                {
                    System.Diagnostics.Debug.WriteLine($"MessageBox fallback error: {ex2.Message}");
                    Console.WriteLine($"SYNC MESSAGE: {title} - {message}");
                }
            }
        }
    }
}
